server:
  port: 8083
  connection-timeout: 60000
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.159.128:9300
  jackson:
    default-property-inclusion: non_null #把是null的值排除
  rabbitmq:
    host: 121.89.222.108
    virtual-host: leyou
    username: leyou
    password: leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 1000    #拉取微服务的时间
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15