server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false  #关闭缓存
  rabbitmq:
    host: 121.89.222.108
    virtual-host: leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance: #心跳时间，自己加的
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15 # 10秒不发送就过期