server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 121.89.222.108
    virtual-host: leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4G49fk7jEM4Nw89yf23A # 你自己的accessKeyId
    accessKeySecret: JDGLZulANyuDvJOQr7zKEOFcFKDGGA # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称